import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { routes } from "../src/data/routes.js";
import { codaRoutes } from "../src/data/coda-routes.js";
import { site } from "../src/data/site-content.js";
import { findWork } from "../src/data/work-items.js";
import { renderAbout } from "./templates/about.mjs";
import { renderHome } from "./templates/home.mjs";
import { renderShell } from "./templates/site-shell.mjs";
import { renderWorkDetail } from "./templates/work-detail.mjs";
import { renderWorkIndex } from "./templates/work-index.mjs";
import { renderCodaPage, renderCodaShell } from "./templates/coda.mjs";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function pageData(route) {
  const locale = route.locale;

  if (route.page === "home") {
    const copy = site.home[locale];
    return {
      active: "home",
      meta: { title: copy.metaTitle, description: copy.metaDescription },
      body: renderHome(route)
    };
  }

  if (route.page === "about") {
    const copy = site.about[locale];
    return {
      active: "about",
      meta: { title: copy.metaTitle, description: copy.metaDescription },
      body: renderAbout(route)
    };
  }

  if (route.page === "work-index") {
    return {
      active: "work",
      meta: {
        title: locale === "th" ? "ผลงาน — Dhittawat Thongkhum" : "Work — Dhittawat Thongkhum",
        description: locale === "th"
          ? "ผลงานออกแบบผลิตภัณฑ์ 11 โครงการของ Dhittawat Thongkhum"
          : "Eleven product-design projects by Dhittawat Thongkhum."
      },
      body: renderWorkIndex(route)
    };
  }

  const item = findWork(route.slug);
  if (!item) throw new Error(`Missing work data for ${route.slug}`);

  return {
    active: "work",
    meta: { title: item[locale].seoTitle, description: item[locale].seoDescription },
    body: renderWorkDetail(item, route)
  };
}

for (const route of routes) {
  const data = pageData(route);
  const html = `<!-- Generated by scripts/generate-pages.mjs. Do not edit directly. -->\n${renderShell({ route, ...data })}`;
  const output = resolve(projectRoot, route.file);

  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, html, "utf8");
}

for (const route of codaRoutes) {
  const data = renderCodaPage(route);
  const html = `<!-- Generated by scripts/generate-pages.mjs. Do not edit directly. -->\n${renderCodaShell({ route, ...data })}`;
  const output = resolve(projectRoot, route.file);

  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, html, "utf8");
}

console.log(`Generated ${routes.length} existing and ${codaRoutes.length} Coda localized HTML pages.`);
